### ISSUE TITLE
this.socket.off is not a function

### ISSUE THREAD

**Issue by Hitoshi1337** [Dev-Yukine/Kurasuta#20]
Im getting error 'TypeError: this.socket.off is not a function' idk in which files but thoce are my files:
```const { BaseCluster } = require('kurasuta');
const { Token } = require('./Config/AspektConfig');

module.exports = class extends BaseCluster {
	launch() {
		this.client.login(Token)
	}
};```
and
```// Packages
const { ShardingManager } = require('kurasuta');
const { join } = require('path');

// Config
const { Token } = require('./Config/AspektConfig');

const sharder = new ShardingManager(join(__dirname, 'AspektStruct'), {
	token: Token,
	clusterCount: 1,
	guildsPerShard: 100,
	respawn: true
});

sharder.spawn();```

**Comment by Dev-Yukine** [comment]
This sounds like an issue with the generated socket for the ipc, can you try using tcp (add a port for `ShardingManagerOption#ipcSocket` to activate that) and tell me if that fixes it?

**Comment by Dev-Yukine** [comment]
This should be fixed with the latest commit, i changed that it defaults to tcp instead using sockets now to make it more user friendly, let me know if you have any issues related to that.
